site_name: Go basic concepts
site_url: https://example.com/
nav:
  - Home: index.md
  - Concepts:
    - Documentation: 'concepts/01-documentation.md'
    - Makefile: 'concepts/02-makefile.md'
    - Building: 'concepts/03-building.md'
    - Routing: 'concepts/04-routing.md'
    - Logging: 'concepts/05-logging.md'
    - Configuration: 'concepts/06-configuration.md'
    - Database: 'concepts/07-database.md'
    - OpenAPI: 'concepts/08-openapi.md'
    - Testing: 'concepts/09-testing.md'
theme: readthedocs