package main

import (
	"bufio"
	"fmt"
	"strings"

	"consoledot-go-template/internal/config"
)

func main() {
	config.Initialize("")

	fmt.Printf("#\n# Copy this file as config/api.env, the syntax is KEY=value.\n")
	fmt.Printf("# This file was generated by 'make generate-example-config'.\n")

	help, err := config.HelpText()
	if err != nil {
		panic(err)
	}

	s := bufio.NewScanner(strings.NewReader(help))
	for s.Scan() {
		fmt.Printf("# %s\n", s.Text())
	}

	fmt.Printf("#\n\n")
}
